version: 2
jobs:
  front_build_and_test:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "front/package.json" }}
            - v1-dependencies-
      - run:
          name: Install dependencies
          command: |
            cd front
            npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "front/package.json" }}
      - run:
          name: Run tests
          command: |
            cd front
            npm test
      - store_test_results:
          path: test-results
  front_deploy_to_staging:
    docker:
      - image: google/cloud-sdk
    environment:
      - CLIENT_APP: 'client-app'
      - SERVER_APP: 'server-app',
      - GOOGLE_PROJECT_ID: 'nuxt-web-app'
      - GOOGLE_COMPUTE_ZONE: 'asia-southeast1-a'
      - GOOGLE_CLUSTER_NAME: 'nuxt-web-app-cluster'
    steps:
      - checkout
      - run:
          name: Setup Google Cloud SDK
          command: |
            cd front
            apt-get install -qq -y gettext
            echo $GCLOUD_SVC_KEY > ${HOME}/gcloud-service-key.json
            gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
            gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
            gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
            gcloud --quiet container clusters get-credentials ${GOOGLE_CLUSTER_NAME}
      - setup_remote_docker:
          version: 18.06.0-ce
      - run:
          name: Docker build and push
          command: |
            gcloud auth print-access-token | docker login -u oauth2accesstoken --password-stdin https://asia.gcr.io
            envsubst < deploy.sh > patched_deploy.sh
            bash patched_deploy.sh
            kubectl rollout status deployment/client-deployment
            kubectl rollout status deployment/server-deployment
          
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - front_build_and_test
      - front_deploy_to_staging:
          requires:
            - front_build_and_test
          filters:
            branches:
              only: master
